on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: install ember-cli
      run: npm install -g ember-cli

    - name: Setup Ember.js Addon
      run: |
        npm install

    - name: Run ember test
      run:
        ember test

    - name: Notify slack build result
      uses: homoluctus/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: '*Ember test*'
          mention: 'here'
          username: 'GitHub Actions'
          mention_if: 'failure'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
