name: Release Gem

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Bundle Install
      run: |
        bundle config --delete deployment
        bundle install --no-deployment
        bundle update --jobs 4 --retry 3

    - name: Build gem
      run: |
        bundle exec rake clean_assets copy_assets build

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${{ secrets.GITHUB_TOKEN }}\n" > $HOME/.gem/credentials
        gem push --key github --host https://rubygems.pkg.github.com/mugijiru pkg/*.gem

    - name: Notify slack publish result
      uses: lazy-actions/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: '*Gem Publish*'
          username: 'GitHub Actions'
          mention_if: 'failure'
          mention: 'here'
          channel: '#develop'
          icon_emoji: 'gem'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
