name: ReviewDog

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: install ember-cli
      run: yarn global add ember-cli

    - name: Setup Ember.js Addon
      run: |
        npm install

    - name: Run reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        npx eslint -f rdjson . | reviewdog -f=rdjson -reporter=github-pr-review

    - name: Notify slack build result
      uses: lazy-actions/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: '*ReviewDog*'
          mention: 'here'
          username: 'GitHub Actions'
          icon_emoji: 'dog'
          mention_if: 'failure'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
